### ISSUE TITLE
Question on Using the wrapper.

### ISSUE THREAD

**Issue by JacoFourie** [hansiglaser/pas-libusb#5]
Hi.

I understand what I need to do but I dont understand the last part to get bulk transfers to work. I want to create a simple program that sends a command and waits for a response. I know what the 2 endpoints are. Can you please show me how to write the code for the bulk transfers on the endpoints ?

```
program usb2;

Uses SysUtils,LibUsb,LibUsbOop,CTypes;


Const DevVID = $067b;
      DevPID = $2303;
      OutEndpoint_address = $02;
      InEndpoint_address = $83;

Var Context                : TLibUsbContext;
    Device                 : TLibUsbDevice;
    DeviceInterface        : TLibUsbInterface;
    OutEndPoint_handle     : TLibUsbEndpoint;
    InEndPoint_handle      : TLibUsbEndpoint;
    OutEndPoint            : TLibUsbBulkOutEndpoint;



begin

  WriteLn('Create Context ..');
  // create context
  Context := TLibUsbContext.Create;
  WriteLn('Context Created..');

  try

    WriteLn('Connect to Device ..');

    //Connect to the device
    Device := TLibUsbDevice.Create(Context,DevVID,DevPID);
    WriteLn('Connected to the Device ..');

    WriteLn('Create OUT EndPoint handle ..');
    OutEndPoint_handle := TLibUsbEndpoint.Create(Device , OutEndpoint_address);
    WriteLn('Created OUT EndPoint handle ..');

    WriteLn('Create IN EndPoint handle ..');
    InEndPoint_handle := TLibUsbEndpoint.Create(Device , InEndpoint_address);
    WriteLn('Created IN EndPoint handle ..');


    //I want to do a bulk transfer to send


    //And then do a bulk transfer to read here when the data is back.



  except
    on E :Exception do begin
       WriteLn(E.Message);
    end;

  end;

  Device.Free;
  Context.Free;


end.
```

**Comment by hansiglaser** [comment]
Hi!

Am Donnerstag, den 26.09.2019, 23:20 -0700 schrieb JacoFourie:
> Hi.
> I understand what I need to do but I dont understand the last part to
> get bulk transfers to work. I want to create a simple program that
> sends a command and waits for a response. I know what the 2 endpoints
> are. Can you please show me how to write the code for the bulk
> transfers on the endpoints ?

Please see
https://github.com/hansiglaser/pas-libusb/blob/libusb-1.0/src/examples/mydevice.pas
as example including bulk endpoints. Oh, I see it just doesn't
communicate via them. :-) Sorry for that.

You have to instantiate TLibUsbBulkInEndpoint and
TLibUsbBulkOutEndpoint (and never the base class TLibUsbEndpoint as in
your example). Please see mydevice.pas on how to create these
instances.

To send and receive, please just see the methods in the two classes in
https://github.com/hansiglaser/pas-libusb/blob/libusb-1.0/src/libusboop.pas. Please also read the documentation of libusb (especially on error
handling, timeouts, ...), because pas-libusb is only a thin wrapping
layer.

Bye
  Hansi

**Comment by JacoFourie** [comment]
OK I think I have it working now. I need to get the Interface first and then the endpoint by looking for it by address. Is this correct now?

Regards.

```
begin

  WriteLn('Create Context ..');
  // create context
  Context := TLibUsbContext.Create;
  WriteLn('Context Created..');

  try

    WriteLn('Connect to Device ..');
    //Connect to the device
    Device := TLibUsbDevice.Create(Context,DevVID,DevPID);
    WriteLn('Connected to the Device ..');

    WriteLn('Get the interface ..');
    //Get the interface
    DeviceInterface := TLibUsbInterface.Create(Device , Device.FindInterface);
    WriteLn('Got the interface ..');

    WriteLn('Create OUT EndPoint ..');
    OutEndPoint := TLibUsbBulkOutEndpoint.Create(DeviceInterface , DeviceInterface.FindEndpoint(OutEndpoint_address));
    WriteLn('Created OUT EndPoint ..');

    WriteLn('Send Data ..');
    send_data := '123456789';
    result_code := OutEndPoint.Send(send_data , send_data.Length ,10);
    WriteLn('Data sent .. Result code ' , result_code : 2 );



    WriteLn('Create IN EndPoint ..');
    InEndPoint := TLibUsbBulkInEndpoint.Create(DeviceInterface , DeviceInterface.FindEndpoint(InEndpoint_address));
    WriteLn('Created IN EndPoint ..');

    WriteLn('Waiting for inbound data ..');
    result_code := InEndPoint.Recv(data , 10 , 10000);


    if(result_code < 0) then
    begin
         WriteLn('Receive error ..  ' + Context.ErrorName(result_code));
    end
    else
    begin
         WriteLn('Data received .. Number of bytes ' , result_code : 2 );
    end;


    If(Device.IsPresent) then
    begin
       WriteLn('The device is still connected ..');
    end
    else
    begin
       WriteLn('The device is not connected ..');
    end;



  except
    on E :Exception do begin
       WriteLn(E.Message);
    end;

  end;

  Device.Free;
  Context.Free;


end.
```

**Comment by hansiglaser** [comment]
Hi!

Am Samstag, den 28.09.2019, 03:35 -0700 schrieb JacoFourie:
> OK I think I have it working now. I need to get the Interface first
> and then the endpoint by looking for it by address. Is this correct
> now?

Yes, endpoints are "owned" by interfaces (same as in the USB
descriptor).

One little warning: In contrast to your example code, I would first
create all Pascal class instances, and then start the communication
with Send and Recv.

Bye
  Hansi

**Comment by JacoFourie** [comment]
Hi. I am new to Lazarus. I just want to make sure I understand. What do you mean by "create all Pascal class instances, and then start the communication with Send and Recv" ?

The device I need to communicate via USB is a HID device. IT has a simple protocol. I send a command and the device will send data back or a ACK / NAC. Do you have a sample program where you use a HID device. Just a simple one with one endpoint?

**Comment by hansiglaser** [comment]
Hi!

Am Sonntag, den 29.09.2019, 09:40 -0700 schrieb JacoFourie:
> Hi. I am new to Lazarus. I just want to make sure I understand. What
> do you mean by "create all Pascal class instances, and then start the
> communication with Send and Recv" ?

May I direct you to an introduction on object oriented programming in
FreePascal at
https://wiki.lazarus.freepascal.org/Object_Oriented_Programming_with_Free_Pascal_and_Lazarus#Class
?

So, in summary, my recommendation means the following _order_:
  OutEndPoint := TLibUsbBulkOutEndpoint.Create(...);
  InEndPoint  := TLibUsbBulkInEndpoint.Create(...);
  result_code := OutEndPoint.Send(...);
  result_code := InEndPoint.Recv(...);

> The device I need to communicate via USB is a HID device. IT has a
> simple protocol. I send a command and the device will send data back
> or a ACK / NAC. Do you have a sample program where you use a HID
> device. Just a simple one with one endpoint?

As far as I know, HID is not that simple.

If the device is so simple as you write, then you can use the approach
discussed so far.

If the device is really a HID device, then I'd like to point to the
FreePascal mailing list thread "USB Human Interface Devices" available
at
https://lists.freepascal.org/pipermail/fpc-pascal/2019-July/thread.html
and continued at
https://lists.freepascal.org/pipermail/fpc-pascal/2019-August/thread.html

I provided some help to James Richters, and he translated my old
"simple HID" class to the new LibUSB OOP wrapper version. However,
after some time, he changed to another approach and I didn't continue
following the discussion.

May I ask you to read the mail thread and possibly contact James for
the latest version of his files. IIRC, he cloned my Git repository and
commited his work. Please keep me in CC. I'd be happy if I could
integrate his work in my version, if we find the latest and greatest of
his work.

Thanks
  Hansi

**Comment by JacoFourie** [comment]
Aaa OK so basically what you said is create all the objects first and then use the methods on them. OK cool, I understand. 

So are you not going to maintain this pas library binding for LibUSB ? I see there are now new functions called "hotplug" that tells you when a USB device is plugged in and removed. I see it is not in your binding yet. I can try and add it I guess, I just don't know Lazarus that well yet. I am more an Oracle PL/SQL developer.

**Comment by JacoFourie** [comment]
Hi. Do you have a sample on how to use a Control Transfer using this lib. I know how to do everything else. all I need is a sample on how to do a Control Transfer.

regards.

**Comment by hansiglaser** [comment]
Hi!

I'm sorry for the late reply.

Am Mittwoch, den 02.10.2019, 04:57 -0700 schrieb JacoFourie:
> Aaa OK so basically what you said is create all the objects first
> and then use the methods on them. OK cool, I understand.

Exactly.

> So are you not going to maintain this pas library binding for
> LibUSB? I see there are now new functions called "hotplug" that
> tells you when a USB device is plugged in and removed. I see it
> is not in your binding yet. I can try and add it I guess, I
> just don't know Lazarus that well yet. I am more an Oracle
> PL/SQL developer.

I am maintaining pas-libusb, but I don't permanently track each change
in LibUSB. I only adapt pas-libusb, if the need arises, either for my
own projects, or for other users via Github or the Freepascal mailing
lists.

Am Samstag, den 05.10.2019, 11:52 -0700 schrieb JacoFourie:
> Hi. Do you have a sample on how to use a Control Transfer using this
> lib. I know how to do everything else. all I need is a sample on how
> to do a Control Transfer.

Please see
https://github.com/hansiglaser/pas-libusb/blob/libusb-1.0/src/examples/test2controlsync.pas
(all uses of the variable EP0) with a demonstration on USB standardized
control endpoint transfers like GetDescriptor, GetString.

Please also see
https://github.com/hansiglaser/pas-libusb/blob/libusb-1.0/src/examples/mydevice.pas
in the methods TMyDevice.SendCommand/In/Out for custom (=vendor
specific) control transfers.

Note 1: TMyDevice descends from TLibUsbDevice, therefore it can
directly access its internal field FControl. In test2controlasync.pas,
this is externally accessed (by getting a reference into variable EP0).

Note 2: Control transfers via endpoint 0 are always for the (whole)
device, and not for an interface (as all "normal" transfers like bulk
transfers).

Bye
  Hansi

**Comment by JacoFourie** [comment]
Hi Hansi. 

All I need to do is send a command via a Control Transfer using a control transfer method. This is what is used in Python "dev.ctrl_transfer(0x21, 0x9, 0x200, 0, cmd)" The first four parameters are the bmRequestType, bmRequest, wValue and wIndex. Command is the command message I need to send.

Can you give me just the steps to define a Control Transfer Endpoint and just use a send method on that endpoint? If you use the code I gave you at the top.  The data is returned on an interrupt endpoint.

I am sorry I am bugging you but your samples are way more complicated for this beginner and for what I need. 

Thanks a lot for the help thus far.

**Comment by JacoFourie** [comment]
OK wait I think I have it. I need to add a Control handle and then use the methods on the EP0 handle.

 EP0 := Device.Control;

**Comment by JacoFourie** [comment]
Hi Hansi.

I can not get the Lazarus to work. I am not sure how to write the concatenated part. I have the code working in Python. Can you please help me write the same in Lazarus. Don't worry about the CRC stuff. It is working in Lazarus.

Here is the Python. I need help with the " getResult" procedure

```
import usb.core, usb.util, usb.control
import crc16
import time

vendorId = 0x0665
productId = 0x5161
interface = 0

dev = usb.core.find(idVendor=vendorId, idProduct=productId)

if dev.is_kernel_driver_active(interface):
    dev.detach_kernel_driver(interface)

dev.set_interface_altsetting(0,0)


def getCommand(cmd):
    cmd = cmd.encode('utf-8')
    crc = crc16.crc16xmodem(cmd).to_bytes(2,'big')
    cmd = cmd+crc
    cmd = cmd+b'\r'
    while len(cmd)<8:
        cmd = cmd+b'\0'
    return cmd

def sendCommand(cmd):
    dev.ctrl_transfer(0x21, 0x9, 0x200, 0, cmd)

def getResult(timeout=100):
    res=""
    i=0
    while '\r' not in res and i<20:
        try:
            res+="".join([chr(i) for i in dev.read(0x81, 8, timeout) if i!=0x00])           
        except usb.core.USBError as e:
            if e.errno == 110:
                print('Timeout')
                pass
            else:
                raise
        i+=1
    return res


run = True

while run:
    sendCommand(getCommand('COMMAND STRING'))
    res = getResult()
    print(res)
    time.sleep(0.2)

```

Here is the Lazarus code. I can connect but not sure why I can not see any data.

```

program usb2;

Uses SysUtils,LibUsb,LibUsbOop ,Classes;


Const DevVID = $0665;
      DevPID = $5161;
      OutEndpoint_address = $02;
      InEndpoint_address = $81;

Var Context                : TLibUsbContext;
    Device                 : TLibUsbDevice;
    DeviceInterface        : TLibUsbInterface;
    OutEndPoint            : TLibUsbDeviceControlEndpoint;
    InEndPoint             : TLibUsbInterruptInEndpoint;
    result_code            : Integer;
    send_data              : String;
    data                   : String;
    send_command           : String;
    command : array[1..8] of Byte;


procedure connect;
begin

    WriteLn('Connect to Device ..');
    //Connect to the device

    try

       WriteLn('Trying to connect to the Device ..');
       Device := TLibUsbDevice.Create(Context,DevVID,DevPID);
    except
    on E :Exception do begin
       WriteLn('Can not conect. Please plug in the device');
    end;
    end;

    while not Assigned(Device) do
    begin

       try

        sleep(1000);
        WriteLn('Cound not connect trying again ..');
        WriteLn('Trying to connect to the Device ..');
        Device := TLibUsbDevice.Create(Context,DevVID,DevPID);

        except
        on E :Exception do begin
           WriteLn('Can not conect. Please plug in the device');
           end;
        end;
    end;

    WriteLn('Connected to the Device ..');


    //Get the interface
    WriteLn('Get the interface ..');
    DeviceInterface := TLibUsbInterface.Create(Device , Device.FindInterface);
    WriteLn('Got the interface ..');

    //Get the IN End Point
    WriteLn('Create IN EndPoint ..');
    InEndPoint := TLibUsbInterruptInEndpoint.Create(DeviceInterface , DeviceInterface.FindEndpoint(InEndpoint_address));
    WriteLn('Created IN EndPoint ..');

    //Get the OUT End Point
    WriteLn('Create OUT EndPoint ..');
    OutEndPoint := Device.Control;
    WriteLn('Created OUT EndPoint ..');




end;

procedure disconnect;
begin

   //Free all the endpoints
   WriteLn('Free In End Point');
   FreeAndNil(InEndPoint);
   WriteLn('Free Out End Point');
   FreeAndNil(OutEndPoint);
   WriteLn('Free Device');
   FreeAndNil(Device);

end;


begin

  // Create context
  WriteLn('Create Context ..');
  Context := TLibUsbContext.Create;
  WriteLn('Context Created..');

  try

    //Connect to the device
    connect;


          WriteLn('Send Command ..');
          OutEndPoint.ControlMsg($21 , $9 , $200 , $0 , command , 8 , 100);
          WriteLn('Command sent ..');


          WriteLn('Waiting for Data ..');
          result_code := InEndPoint.Recv(data , 8 , 1000);
          WriteLn('Data Received ..');

          WriteLn(result_code);
          writeLn(data);



    disconnect;



  except
    on E :Exception do begin
       WriteLn(E.Message);
    end;

  end;


end.
```

**Comment by hansiglaser** [comment]
Hi!

Sorry for the late reply.

As far as I can see, it seems that you don't properly create the
command before sending it. The variable "command" in your Pascal code
is totally uninitialized, while in the Python code the special function
getCommand() does quite some magic including calculating a CRC and
padding to 8 bytes.

And secondly, in the Python code, the EP1IN is queried in a loop until
enough data is received, while in your code you just execute Recv()
once.

So, IMHO, the majority of your problems are not related to USB, but to
the general data handling, which is out of the scope of pas-libusb.

Bye
  Hansi

**Comment by JacoFourie** [comment]
Hi Hansi. As stated do not worry about the CRC. I hard coded the command just for testing. If I try to print the data that comes back I get an access violation error. 

writeLn(data);   gives the error. Why would it do that. The return code is 8 so there should be 8 bytes in the string.

**Comment by JacoFourie** [comment]
Hi Hansi. How do I call these 2 settings using your pas file?  I have the data handling sorted out but now it seems I have a loopback. What I send out on the out endpoint I get back in the in end point. The only difference between my Python code and the Lazarus code is the alt settings are not set in my code in Lazarus.

    dev.detach_kernel_driver(interface)
    dev.set_interface_altsetting(0,0)

I see them in the class TLibUsbInterface but they are private and I can not call them from my code.

 ```
 TLibUsbInterface = class
  private
    FDevice     : TLibUsbDevice;
    FInterface  : Plibusb_interface_descriptor;
    FIntfNum    : Byte;
    FAltSetting : Byte;
    Procedure Claim;
    Procedure Release;
    Procedure SetAltSetting;
    Function  IsKernelDriverActive : Boolean;
    Procedure DetachKernelDriver;
    Procedure AttachKernelDriver;
  public
    Constructor Create(ADevice:TLibUsbDevice;AInterface:Plibusb_interface_descriptor);
    Destructor Destroy; override;
    Function  FindEndpoint(MatchFunc :TLibUsbEndpointMatchMethod                  ) : Plibusb_endpoint_descriptor;
    Function  FindEndpoint(MatchClass:TLibUsbEndpointMatchClass;CFree:Boolean=True) : Plibusb_endpoint_descriptor;
    Function  FindEndpoint(MatchFunc :TLibUsbEndpointMatchFunc;Data:Pointer       ) : Plibusb_endpoint_descriptor;
    Function  FindEndpoint(bEndpointAddress:Byte                                  ) : Plibusb_endpoint_descriptor;
    property Descriptor : Plibusb_interface_descriptor read FInterface;
    property IntfNum    : Byte read FIntfNum;
    property AltSetting : Byte read FAltSetting;
  End;  
```

**Comment by JacoFourie** [comment]
Hi Hansi.

I am almost there. What I did now was to send the command with the python code and not read the data and then when I fire up the Lazarus code I get data in the buffer back. So my Interrupt endpoint is working fine. I now just need to figure out how to send the Control Transfer correctly as it seems it is in loopback mode at this stage. I am sooo close I can taste it lol.

I send the command like this.

result_code := Device.Control.ControlMsg($21 , $9 , $0200 , $0 , command , 8 , 100);

Is that the correct way?

**Comment by JacoFourie** [comment]
I got it working !!

**Comment by hansiglaser** [comment]
Hi!

You can not simply use the datatype string to store the "data" value given by TLibUsbInterruptInEndpoint.Recv. Please see its declaration: It has an anonymous "Out" parameter, for which you first have to allocate the space (on heap or simpler on space with e.g., a local variable of type Array of Byte[0..7]).

Regarding the interface alt setting and the kernel attachment: I'm sorry, but I can't recall why I made these functions private. You can just move them to the public section.

Nevertheless, I'm glad to hear that you got it working!

Bye
  Hansi
