### ISSUE TITLE
How to release the device if you loose USB connection ?

### ISSUE THREAD

**Issue by JacoFourie** [hansiglaser/pas-libusb#6]
Hi Hansi.

So I got the comms working. I am now working on the code that will retry to connect to the device again if I lose a connection. If I call the code Device.Free if I plug out the USB cable then the program will hang at that point.

What I am doing is to check the status of Device.IsPresent. If that goes to False I will Free all the endpoint and interface. That works fine but when I get to the Device it will hang. How do I release all the objects and try again if the USB device is unplugged?

**Comment by hansiglaser** [comment]
Hi!

Could you please provide a backtrace so we can see where _exactly_ the program is hanging?

To do this, for example, start the program in GDB, reproduce the hang, then type ^C. Then use the "bt" command of GDB to print the backtrace.

IIRC, this should also be possible from within Lazarus (but I don't recall how to interrupt a running program without completely quitting it). Then please provide the full content of the backtrace window.

Thanks
  Hansi

**Comment by JacoFourie** [comment]
Here is the code

```
procedure disconnect;
begin

   //Free all the endpoints
   WriteLn('Free In End Point');
   //InEndPoint.Free;
   FreeAndNil(InEndPoint);
   WriteLn('Free Out End Point');
   //OutEndPoint.Free;
   FreeAndNil(OutEndPoint);
   WriteLn('Free Device');
   try
      //halt;
      //Device.CleanupInstance;
      Device.Free;
      //FreeAndNil(Device);
      //WriteLn('Device freed');

   except
        on E :Exception do begin
           WriteLn(E.Message);
           end;
        end;

end;
```

Here is the back trace. 

```
(gdb) bt
#0  0x0009ba3e in CLASSES$_$TWRITER_$__$$_CREATE$TSTREAM$LONGINT$$TWRITER ()
#1  0x00030610 in SYSTEM$_$TOBJECT_$__$$_FREE ()
#2  0x00011660 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

The program works 100% then I pull out the USB cable. I then free all the objects and when I get to Device it will hang.

```
237.3 49.9 237.3 49.9 0023 0014 000 428 53.20 000 100 0034 0000 000.0 00.00 00000 00010101 00 0
Free In End Point
Free Out End Point
Free Device
```

**Comment by JacoFourie** [comment]
I got it working.

**Comment by hansiglaser** [comment]
Great to hear!
The backtrace points to the constructor of TWriter. I'm pretty sure this is not used anywhere in pas-libusb. So I guess the problem was outside of it.
