### ISSUE TITLE
Works on Raspberry Pi4 but not On Pi 3

### ISSUE THREAD

**Issue by JacoFourie** [hansiglaser/pas-libusb#7]
Hi. I wrote a program and it works very well on the Pi 4. But when I run the same code on the Pi 3 
I will get random time outs and corrupt data. How do I go about trying to find why it does not work on the Pi 3?

**Comment by hansiglaser** [comment]
Hi!

Am Mittwoch, den 29.01.2020, 12:56 -0800 schrieb JacoFourie:
> Hi. I wrote a program and it works very well on the Pi 4. But when I
> run the same code on the Pi 3
> I will get random time outs and corrupt data. How do I go about
> trying to find why it does not work on the Pi 3?

This sounds strange. I doubt that the hardware is the problem. What are
all the differences between the two cases? Which OS and which version,
library versions, compiler, kernel, connection to the device, hubs, ...

Bye
  Hansi

**Comment by JacoFourie** [comment]
I got it working thanks.

**Comment by hansiglaser** [comment]
Hi!

Am Dienstag, den 04.02.2020, 10:34 -0800 schrieb JacoFourie:
> I got it working thanks.

Great to hear!

Could you please describe your solution, so that this thread is of help
for other users too?

Thanks
  Hansi
